declare namespace NodeJS {
  interface ProcessEnv {
    MEDUSA_BACKEND_URL: string;
    MEDUSA_PUBLISHABLE_KEY: string;
    NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: string;
    NEXT_PUBLIC_POSTHOG_PROJECT_TOKEN?: string;
    NEXT_PUBLIC_POSTHOG_HOST?: string;
    NEXT_PUBLIC_POSTHOG_SESSION_REPLAY?: string;
    CHECKOUT_HANDOFF_SECRET?: string;
    CHECKOUT_HANDOFF_TTL_SECONDS?: string;
    KV_REST_API_URL?: string;
    KV_REST_API_TOKEN?: string;
    UPSTASH_REDIS_REST_URL?: string;
    UPSTASH_REDIS_REST_TOKEN?: string;
    STRIPE_SECRET_KEY?: string;
    RESEND_API_KEY?: string;
    ORDER_EMAIL_FROM?: string;
    ORDER_NOTIFICATION_EMAIL?: string;
    ORDER_EMAIL_TEST_SECRET?: string;
    ADMIN_PASSWORD?: string;
    UPS_CLIENT_ID?: string;
    UPS_CLIENT_SECRET?: string;
    USPS_CLIENT_ID?: string;
    USPS_CLIENT_SECRET?: string;
    NEXT_PUBLIC_SITE_URL?: string;
    SATIELLE_MEDUSA_VARIANT_ID?: string;
    RETATRUTIDE_MEDUSA_VARIANT_ID?: string;
    SEMAGLUTIDE_MEDUSA_VARIANT_ID?: string;
    TIRZEPATIDE_MEDUSA_VARIANT_ID?: string;
    VELLURACARE_MEDUSA_VARIANT_ID?: string;
  }
}
